service:
  log_file: "/var/log/kc-go.log"

check:
  url: "http://connect.rom.miui.com/generate_204"
  interval: 1

account:
  user: "YOUR_ACCOUNT"
  password: "YOUR_PASSWORD"

cloudflare:
  # 获取: https://dash.cloudflare.com/profile/api-tokens
  token: ""
  zone_id: ""
  domains:
    # true = 更新对应 A/AAAA 记录
    - name: "example.com"
      ipv4: true
      ipv6: false
